FROM golang:alpine3.23

# Update
RUN apk update

# install tesseract and language packs
RUN apk install -y libtesseract-dev libleptonica-dev
RUN apk install -y tesseract-ocr-eng tesseract-ocr-deu

# install deps
WORKDIR /tmp/app
COPY go.mod go.sum ./
RUN go mod download

# build project
COPY . .
RUN go build -o /app/main .

# serve
WORKDIR /app
ENTRYPOINT ["./main"]