FROM pytorch/pytorch:2.4.1-cuda12.4-cudnn9-devel

RUN apt-get update

# # install tesseract and german language pack
# RUN apt install -y tesseract-ocr libtesseract-dev
# RUN apt-get install -y tesseract-ocr-deu


# install python dependencies
RUN pip install \
fastapi \
    pillow \
    uvicorn \
    python-multipart \
    transformers \
    sentencepiece \
    nltk \
    zss \
    sconf \
    protobuf

# pre load models
RUN python -c "from transformers import DonutProcessor, VisionEncoderDecoderModel; DonutProcessor.from_pretrained('naver-clova-ix/donut-base-finetuned-cord-v2'); VisionEncoderDecoderModel.from_pretrained('naver-clova-ix/donut-base-finetuned-cord-v2')"

WORKDIR /app
COPY . .

# # preload models
# RUN python load_models.py

# ENTRYPOINT [ "python", "run.py" ]
# ENTRYPOINT [ "/bin/bash" ]
ENTRYPOINT [ "uvicorn", "run:app", "--host", "0.0.0.0", "--port", "10000" ]