// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package datamodel

import (
	"context"

	"github.com/google/uuid"
)

const getDocumentData = `-- name: GetDocumentData :many
SELECT uuid FROM DocumentHub
`

func (q *Queries) GetDocumentData(ctx context.Context) ([]uuid.NullUUID, error) {
	rows, err := q.db.QueryContext(ctx, getDocumentData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.NullUUID{}
	for rows.Next() {
		var uuid uuid.NullUUID
		if err := rows.Scan(&uuid); err != nil {
			return nil, err
		}
		items = append(items, uuid)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
