FROM ubuntu:20.04

# Install dependencies
RUN apt-get update

# install tesseract and german language pack
RUN apt install -y tesseract-ocr libtesseract-dev
RUN apt-get install -y tesseract-ocr-deu

# Install python 3.10
RUN apt-get update && \
    apt install -y software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update && \
    apt-get clean
RUN apt-get remove -y python3.8 python2.7 && \
    apt-get autoremove -y && \
    apt-get clean
RUN apt-get install -y python3.10

# setup python environment
RUN apt-get install -y curl && \
    curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10
RUN ln -s /usr/bin/python3.10 /usr/bin/python
RUN python -m pip install --upgrade pip
RUN python -m pip install poetry

# Install OpenCV dependencies
RUN apt-get update && apt-get install -y libgl1-mesa-glx libglib2.0-0 && apt-get clean

# setup app
WORKDIR /app
COPY . .
RUN poetry config virtualenvs.in-project true
RUN poetry install --no-root


ENV TESSDATA_PREFIX=/usr/share/tesseract-ocr/4.00/tessdata/


ENTRYPOINT [ "poetry", "run", "uvicorn", "run:app", "--host", "0.0.0.0", "--port", "8080" ]
# ENTRYPOINT [ "/bin/bash" ]