FROM python:3.10-slim-bullseye

RUN apt-get update

RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0

RUN pip install \
    langchain \
    langchain-community \
    langchain-openai \
    openai

WORKDIR /app
COPY . . 

ENTRYPOINT [ "/bin/bash" ]